 # it gets a little redundant always passing in your Facebook application ID and secret to create new instances of the OAuth class

development:
  app_id: YOUR APP ID
  secret_key: YOUR SECRET
test:
  app_id: YOUR APP ID
  secret_key: YOUR SECRET
production:
  app_id: YOUR APP ID
  secret_key: YOUR SECRET